apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gothenburg-weather-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: gothenburg-weather
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s

